apiVersion: v1
kind: Secret
metadata:
  name: oracle-secret

type: Opaque
stringData:
  APP_USER: {{ .Values.oracle.appUser }}
  APP_USER_PASSWORD: {{ .Values.oracle.appPassword }}
  ORACLE_PASSWORD: {{ .Values.oracle.password }}