apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: oracledb
spec:
  serviceName: oracledb
  replicas: 1
  selector:
    matchLabels:
      app: oracledb
  template:
    metadata:
      labels:
        app: oracledb
    spec:
      containers:
        - name: oracledb
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 1521
          envFrom:
            - secretRef:
                name: oracle-secret
          volumeMounts:
            - name: oracle-data
              mountPath: /opt/oracle/oradata
      volumes:
        - name: oracle-data
          persistentVolumeClaim:
            claimName: oracle-pvc