[project]
name = "transaction-data-processing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "oracledb>=3.4.1",
    "sqlalchemy>=2.0.45",
]

#  uv add sqlalchemy
#  uv add oracledb